apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-testapp
  labels:
    app: testapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: container-testapp
        image: nexus.fwz.ru/testapp:3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-svc
  labels:
    app: testapp
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: testapp
